FROM adoptopenjdk/openjdk11:latest
ADD ../../../target/flight-booking-system-with-spring-boot.jar flight-booking-system-with-spring-boot.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "flight-booking-system-with-spring-boot.jar"]